### ISSUE TITLE
AMD GPU performance mode feedback

### ISSUE THREAD

**Issue by vinifmor** [vinifmor/guapow#1]
Unfortunately, I currently have no AMD GPU to test if the "performance/compute" mode is properly being set. I've coded the behavior and written unit tests though.

The code responsible to make this happen is located [here](https://github.com/vinifmor/guapow/blob/master/guapow/service/optimizer/gpu.py#L172).

Feedback is welcome.

**Comment by vinifmor** [comment]
1) First check the content of the following files:

- /sys/bus/pci/drivers/amdgpu/0/power_dpm_force_performance_level
- /sys/bus/pci/drivers/amdgpu/0/pp_compute_power_profile

2) Then follow the 2 first steps of the [Quick Start section](https://github.com/vinifmor/guapow#quick_start) and keep the media player (vlc or other application you launched) running. 

3) Check if the files contents have changed.

4) Stop the media player.

5) Check if the files have the original content set

(if possible, paste the contents of these files here)

**Comment by Templayer** [comment]
> 1. First check the content of the following files:
> 
> * /sys/bus/pci/drivers/amdgpu/0/power_dpm_force_performance_level
> * /sys/bus/pci/drivers/amdgpu/0/pp_compute_power_profile
> 
> 2. Then follow the 2 first steps of the [Quick Start section](https://github.com/vinifmor/guapow#quick_start) and keep the media player (vlc or other application you launched) running.
> 3. Check if the files contents have changed.
> 4. Stop the media player.
> 5. Check if the files have the original content set
> 
> (if possible, paste the contents of these files here)

I'm going to try that on Friday unless I forget. I've sent an email to myself about this, so I hopefully won't. :D

**Comment by Templayer** [comment]
There is no "0" folder in /sys/bus/pci/drivers/amdgpu/

(used root to check)

![image](https://user-images.githubusercontent.com/11728067/158611347-f58838e0-d416-47cf-81e4-9656854d6916.png)

Opening the 000... 7 folder hard-froze my computer. And when I mean hard, I mean hard. Even the cooling stopped running, but the screen display was stuck on me opening that folder. D: 

![image](https://user-images.githubusercontent.com/11728067/158612118-306b9fe3-e36a-4f83-b41f-606ad37ba27a.png)

**Comment by vinifmor** [comment]
Sorry, I should've mentioned that the "0" could be different for every device. It is basic the device id. Please, try a `cat` command instead of opening through the graphical interface.

e.g: `cat  /sys/bus/pci/drivers/amdgpu/0.0.0.7.../power_dpm_force_performance_level`

**Comment by Templayer** [comment]
I'll be editing this comment after posting the first data, just in the case of a crash or something. Last time I wasn't prepared for the total freeze that happened.

![image](https://user-images.githubusercontent.com/11728067/159510975-c57788f7-2971-4659-a7cc-6aa4dd8a6db0.png)

Looks like that pp thing you have mentioned either has a typo, or I don't have it.

**Comment by Templayer** [comment]
@vinifmor The last comment was appended/edited.

**Comment by vinifmor** [comment]
@Templayer , thanks for the feedback. I will have a look on the missing file.

About the optimizations: you should define the changes. For instance: if you want more CPU priority for a process, you can request a negative nice value (`cpu.nice=-1`). If you want your CPU in maximum performance when target process launches, you can use `cpu.performance`. The project's README file has all the current possibilities.

Example: `GUAPOW_CONFIG="cpu.performance proc.nice=-1" guapow vlc`

You can also create optimization profiles and auto optimizing with the watcher service.

**Comment by Templayer** [comment]
> @Templayer , thanks for the feedback. I will have a look on the missing file.
> 
> About the optimizations: you should define the changes. For instance: if you want more CPU priority for a process, you can request a negative nice value (`cpu.nice=-1`). If you want your CPU in maximum performance when target process launches, you can use `cpu.performance`. The project's README file has all the current possibilities.
> 
> Example: `GUAPOW_CONFIG="cpu.performance proc.nice=-1" guapow vlc`
> 
> You can also create optimization profiles and auto optimizing with the watcher service.

Yeap, I've read the tutorials/documentation. I haven't yet had the needs for the cpu.nice (I can set that from the process manager in Linux Mint) or cpu.performance (I think it's already at that? I think I had that set up - if I'm not on battery power, that is).

For now, I'm just running the default optimization in the watcher for some bigger processes (as you can see from the logs that I've attached in my previous to the last comment) - Brave (a browser derived from Chrome), Java (IntelliJ Idea + the applications that I'm developing), Wine (i.e. anything that runs under it), Cinnamon, SMPlayer,...

> Then follow the 2 first steps of the [Quick Start section](https://github.com/vinifmor/guapow#quick_start) and keep the media player (vlc or other application you launched) running.

Also, the Quick Start section doesn't contain anything about GPU. It only contains cpu.performance. Maybe I should've done the steps provided, but with GPU settings instead? (should have been told in this case, because I'm a bit clueless).

Actually, if I don't set up a profile and just go with default everything, and then just add application names to the map for the watcher, the logs are logging optimization for said applications (well, for some of them) - what is happening there? I could find default optimizations in the documentation. I might just be very drowsy, though. Goddamn sleep-deprivation! :D

**Comment by vinifmor** [comment]
There is no default profile indeed. But you can generate some pre-defined templates with `guapow-cli`. For instance: `guapow-cli gen-profile media` or `guapow-cli gen-profile game`

**Comment by Templayer** [comment]
Nifty, I'll try that out eventually.

> > Then follow the 2 first steps of the [Quick Start section](https://github.com/vinifmor/guapow#quick_start) and keep the media player (vlc or other application you launched) running.
> 
> Also, the Quick Start section doesn't contain anything about GPU in those two first steps. It only contains cpu.performance. Maybe I should've done the steps provided, but with GPU settings instead? (should have been told in this case, because I'm a bit clueless).

What about this? As far as I know, the first two steps just change cpu to performance mode and it doesn't do anything with the GPU, which is what we are trying to test in this Issue?

**Comment by vinifmor** [comment]
You're right. I forgot to mention that. You just need to add the `gpu.performance` property to the config/profile.

**Comment by Templayer** [comment]
Shouldn't launching an application via the steps provided just with gpu.performance instead of cpu.performance be enough? I don't quite see the reason for creating a profile for that. Yet.

**Comment by Templayer** [comment]
Oh, your software thinks I have Nvidia GPUs!

bře 24 10:50:13 JB-PC guapow-opt[1391]: New request: pid: 81041, command: vlc, user_name: jboksa1, created_at: 2022-03-24 10:50:13.818521, config: gpu.performance proc.nice=-1
bře 24 10:50:13 JB-PC guapow-opt[1391]: Nvidia GPUs cannot be managed: 'nvidia-settings' is not installed
bře 24 10:50:13 JB-PC guapow-opt[1391]: Process 81041 nice level changed to '-1' (request=81041)

**Comment by vinifmor** [comment]
It is problably not working because the other AMD files is not available.

In relation to Nvidia: it is just checking if you have the drivers and required software installed.

**Comment by vinifmor** [comment]
you can bypass the checks by setting your GPU model on the optimizer configuration file
